<Project Sdk="Dalamud.CN.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>0.8.2.0</Version>
        <PackageProjectUrl>https://github.com/AtmoOmen/ffxiv_navmesh</PackageProjectUrl>
        <ImplicitUsings>enable</ImplicitUsings>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <NoWarn>1701;1702;CS0414;CS8601;CS8602;CS8604;CS8603;IDE1006;IDE0300;MSB3270;MSB324;CS0649;CA2211;CS8509;CS8625;MSB3305;CS8618;CS8600;CS8605;CS8620;CS0162</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\vnavmesh.Common\vnavmesh.Common.csproj"/>
        <ProjectReference Include="..\vnavmesh.Worker\vnavmesh.Worker.csproj" ReferenceOutputAssembly="false" Private="false"/>
        <ProjectReference Include="..\DotRecast\src\DotRecast.Core\DotRecast.Core.csproj"/>
        <ProjectReference Include="..\DotRecast\src\DotRecast.Detour\DotRecast.Detour.csproj"/>
        <ProjectReference Include="..\DotRecast\src\DotRecast.Detour.Crowd\DotRecast.Detour.Crowd.csproj"/>
        <ProjectReference Include="..\DotRecast\src\DotRecast.Detour.Extras\DotRecast.Detour.Extras.csproj"/>
        <ProjectReference Include="..\DotRecast\src\DotRecast.Recast\DotRecast.Recast.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0"/>
        <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0"/>
        <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0"/>
        <PackageReference Include="SharpDX.Mathematics" Version="4.2.0"/>
        <Reference Include="Dalamud.Common" Private="false"/>
    </ItemGroup>

    <Target Name="CopyNavmeshWorker" AfterTargets="Build">
        <MSBuild Projects="..\vnavmesh.Worker\vnavmesh.Worker.csproj"
                 Targets="GetTargetPath"
                 Properties="Configuration=$(Configuration);Platform=$(Platform)">
            <Output TaskParameter="TargetOutputs" ItemName="NavmeshWorkerTargetPath"/>
        </MSBuild>
        <ItemGroup>
            <NavmeshWorkerFile Include="$([System.IO.Path]::GetDirectoryName('%(NavmeshWorkerTargetPath.Identity)'))\*.*"/>
        </ItemGroup>
        <Copy SourceFiles="@(NavmeshWorkerFile)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true"/>
    </Target>

</Project>
